### ISSUE TITLE
Blank initial value failure

### ISSUE THREAD

**Issue by andrewblake1** [haifahrul/yii2-autonumeric#1]
Good work, I see if you have just released this - was getting over the problems with maskedMoney input and went looking for an alternative this morning.

Minor bug when setting initial value if value is is empty as parseFloat returns 'Nan'. Will fork, fix and submit pull request in a few minutes.

Cheers

**Comment by haifahrul** [comment]
Thank you @andrewblake1

I Will check and merge pull request.

Cheers
